import { Injectable } from '@nestjs/common';
import { z } from 'zod';
import { DbContextService } from '../../../core/auth/db-context.service';
import { Principal } from '../../../core/auth/principal';
import { AuditService } from '../../../shared/audit/audit.service';
import { IdempotencyService } from '../../../shared/idempotency/idempotency.service';
import { PatientsReadPort } from '../../../shared/ports/patients.read-port';
import { AppointmentsReadPort } from '../../../shared/ports/appointments.read-port';
import { ClinicalReadPort } from '../../../shared/ports/clinical.read-port';
import { appointments } from '../../../infrastructure/database/schema';
import { eq, and, isNull } from 'drizzle-orm';
import { ConflictError, ForbiddenError, NotFoundError, ValidationError } from '../../../shared/errors/errors';
import { MarketingRepository } from '../infrastructure/marketing.repository';
import { campaigns, followUpCases, leads, recallCases } from '../../../infrastructure/database/schema';
import { canTransitionCampaign, canTransitionFollowUp, canTransitionLead, canTransitionRecall, CampaignStatus, FollowUpStatus, LeadStatus, RecallStatus } from '../domain/marketing-lifecycle';

const uuid = z.string().uuid();
const date = z.string().regex(/^\d{4}-\d{2}-\d{2}$/, 'date must be YYYY-MM-DD');
const leadInput = z.object({ branchId: uuid, name: z.string().trim().min(2).max(256), phone: z.string().max(64).nullish(), source: z.string().trim().min(1).max(64), interestedTreatment: z.string().max(256).nullish(), assigneeId: uuid.nullish(), patientId: uuid.nullish() });
const campaignInput = z.object({ branchId: uuid, name: z.string().trim().min(2).max(256), intent: z.string().trim().min(1).max(512), audienceDefinition: z.record(z.unknown()), templateReference: z.string().max(256).nullish() });
const ruleInput = z.object({ branchId: uuid, name: z.string().trim().min(2).max(256), treatmentCode: z.string().max(64).nullish(), intervalMonths: z.number().int().positive(), effectiveFrom: date });
const recallInput = z.object({ branchId: uuid, patientId: uuid, recallRuleId: uuid.nullish(), dueDate: date, assigneeId: uuid.nullish(), idempotencyKey: z.string().trim().min(8).max(256) });
const followUpInput = z.object({ branchId: uuid, patientId: uuid, appointmentId: uuid.nullish(), encounterId: uuid.nullish(), assigneeId: uuid.nullish(), dueDate: date });
const statusInput = z.object({ status: z.string(), outcome: z.string().trim().min(1).max(512).nullish() });

/** Marketing records operational intent and cases only. It never sends messages or owns patient/clinical data. */
@Injectable()
export class MarketingService {
  constructor(private readonly dbCtx: DbContextService, private readonly repo: MarketingRepository, private readonly patients: PatientsReadPort, private readonly appointmentsPort: AppointmentsReadPort, private readonly clinical: ClinicalReadPort, private readonly audit: AuditService, private readonly idempotency: IdempotencyService) {}
  private assertAccess(p: Principal) { if (p.role !== 'hq' && p.role !== 'branch_manager') throw new ForbiddenError('Marketing access is restricted to HQ and branch managers'); }
  private branch(p: Principal, requested: string) { if (p.role === 'branch_manager' && p.branchId !== requested) throw new ForbiddenError('Branch manager cannot access another branch'); return requested; }
  private scoped(p: Principal, requested?: string) { return p.role === 'hq' ? (requested ?? null) : p.branchId; }
  private invalid(parsed: { error: { issues: Array<{ path: (string | number)[]; message: string }> } }) { return new ValidationError(Object.fromEntries(parsed.error.issues.map((x) => [x.path.join('.'), [x.message]]))); }
  private parse<T>(schema: z.ZodType<T>, raw: unknown): T { const result = schema.safeParse(raw); if (!result.success) throw this.invalid(result); return result.data; }
  private async ensurePatient(tx: Parameters<PatientsReadPort['getPatientById']>[0], p: Principal, patientId: string, branchId: string) { const patient = await this.patients.getPatientById(tx, p.orgId, patientId); if (!patient) throw new ValidationError({ patientId: ['Unknown patient'] }); if (patient.branchId !== branchId) throw new ForbiddenError('Patient is outside the requested branch'); }
  private auditEvent(p: Principal, action: string, entity: string, id: string, branchId: string, before?: Record<string, unknown>, after?: Record<string, unknown>) { return { actorId: p.staffId, actorRole: p.role, action, entity, entityId: id, orgId: p.orgId, branchId, source: 'api' as const, before, after }; }

  async createLead(p: Principal, raw: unknown) { this.assertAccess(p); const input = this.parse(leadInput, raw); const branchId = this.branch(p, input.branchId); return this.dbCtx.runAs(p, async tx => { if (input.patientId) await this.ensurePatient(tx, p, input.patientId, branchId); const row = await this.repo.createLead(tx, { ...input, branchId, orgId: p.orgId, createdBy: p.staffId, updatedBy: p.staffId, phone: input.phone ?? null, interestedTreatment: input.interestedTreatment ?? null, assigneeId: input.assigneeId ?? null, patientId: input.patientId ?? null }); await this.audit.record(this.auditEvent(p, 'marketing_lead_created', 'leads', row.id, branchId, undefined, { status: row.status, source: row.source }), tx); return row; }); }
  async listLeads(p: Principal, branchId?: string) { this.assertAccess(p); return this.dbCtx.runAs(p, tx => this.repo.listLeads(tx, p.orgId, this.scoped(p, branchId))); }
  async createCampaign(p: Principal, raw: unknown) { this.assertAccess(p); const input = this.parse(campaignInput, raw); const branchId = this.branch(p, input.branchId); return this.dbCtx.runAs(p, async tx => { const row = await this.repo.createCampaign(tx, { ...input, branchId, orgId: p.orgId, createdBy: p.staffId, updatedBy: p.staffId, templateReference: input.templateReference ?? null }); await this.audit.record(this.auditEvent(p, 'marketing_campaign_created', 'campaigns', row.id, branchId, undefined, { status: row.status }), tx); return row; }); }
  async listCampaigns(p: Principal, branchId?: string) { this.assertAccess(p); return this.dbCtx.runAs(p, tx => this.repo.listCampaigns(tx, p.orgId, this.scoped(p, branchId))); }
  async createRecallRule(p: Principal, raw: unknown) { this.assertAccess(p); const input = this.parse(ruleInput, raw); const branchId = this.branch(p, input.branchId); return this.dbCtx.runAs(p, async tx => { const row = await this.repo.createRecallRule(tx, { ...input, branchId, orgId: p.orgId, createdBy: p.staffId, updatedBy: p.staffId, treatmentCode: input.treatmentCode ?? null }); await this.audit.record(this.auditEvent(p, 'recall_rule_created', 'recall_rules', row.id, branchId), tx); return row; }); }
  async createRecallCase(p: Principal, raw: unknown) { this.assertAccess(p); const input = this.parse(recallInput, raw); const branchId = this.branch(p, input.branchId); const scope = `marketing:recall:${p.orgId}:${input.patientId}:${input.recallRuleId ?? 'none'}:${input.dueDate}`; const execution = await this.idempotency.execute(input.idempotencyKey, scope, () => this.dbCtx.runAs(p, async tx => { await this.ensurePatient(tx, p, input.patientId, branchId); if (input.recallRuleId && !await this.repo.findRecallRule(tx, p.orgId, input.recallRuleId)) throw new ValidationError({ recallRuleId: ['Unknown recall rule'] }); const duplicate = await this.repo.findRecallDuplicate(tx, p.orgId, input.patientId, input.recallRuleId ?? null, input.dueDate); if (duplicate) return duplicate; const row = await this.repo.createRecallCase(tx, { orgId: p.orgId, branchId, patientId: input.patientId, recallRuleId: input.recallRuleId ?? null, dueDate: input.dueDate, assigneeId: input.assigneeId ?? null, createdBy: p.staffId, updatedBy: p.staffId }); await this.audit.record(this.auditEvent(p, 'recall_case_created', 'recall_cases', row.id, branchId, undefined, { dueDate: row.dueDate, idempotencyKey: input.idempotencyKey }), tx); return row; })); if (execution.inProgress || !execution.result) throw new ConflictError('Recall creation is already in progress'); return execution.result; }
  async listRecallCases(p: Principal, branchId?: string) { this.assertAccess(p); return this.dbCtx.runAs(p, tx => this.repo.listRecallCases(tx, p.orgId, this.scoped(p, branchId))); }
  async createFollowUp(p: Principal, raw: unknown) { this.assertAccess(p); const input = this.parse(followUpInput, raw); const branchId = this.branch(p, input.branchId); return this.dbCtx.runAs(p, async tx => { await this.ensurePatient(tx, p, input.patientId, branchId); if (input.appointmentId) { const rows = await tx.select({ id: appointments.id, patientId: appointments.patientId }).from(appointments).where(and(eq(appointments.orgId, p.orgId), eq(appointments.id, input.appointmentId), isNull(appointments.deletedAt))).limit(1); const appt = rows[0]; if (!appt) throw new ValidationError({ appointmentId: ['Unknown appointment'] }); if (appt.patientId !== input.patientId) throw new ValidationError({ appointmentId: ['Appointment does not belong to the patient'] }); } if (input.encounterId) { const enc = await this.clinical.getEncounterById(tx, p.orgId, input.encounterId); if (!enc) throw new ValidationError({ encounterId: ['Unknown encounter'] }); if (enc.patientId !== input.patientId) throw new ValidationError({ encounterId: ['Encounter does not belong to the patient'] }); } const row = await this.repo.createFollowUp(tx, { ...input, branchId, orgId: p.orgId, appointmentId: input.appointmentId ?? null, encounterId: input.encounterId ?? null, assigneeId: input.assigneeId ?? null, createdBy: p.staffId, updatedBy: p.staffId }); await this.audit.record(this.auditEvent(p, 'follow_up_created', 'follow_up_cases', row.id, branchId), tx); return row; }); }
  async listFollowUps(p: Principal, branchId?: string) { this.assertAccess(p); return this.dbCtx.runAs(p, tx => this.repo.listFollowUps(tx, p.orgId, this.scoped(p, branchId))); }
  private async transition(p: Principal, id: string, raw: unknown, entity: 'lead' | 'campaign' | 'recall' | 'followUp') { this.assertAccess(p); const input = this.parse(statusInput, raw); return this.dbCtx.runAs(p, async tx => { const before = entity === 'lead' ? await this.repo.findLead(tx,p.orgId,id) : entity === 'campaign' ? await this.repo.findCampaign(tx,p.orgId,id) : entity === 'recall' ? await this.repo.findRecallCase(tx,p.orgId,id) : await this.repo.findFollowUp(tx,p.orgId,id); if (!before) throw new NotFoundError(entity, id); this.branch(p, before.branchId); const okay = entity === 'lead' ? canTransitionLead(before.status as LeadStatus, input.status as LeadStatus) : entity === 'campaign' ? canTransitionCampaign(before.status as CampaignStatus, input.status as CampaignStatus) : entity === 'recall' ? canTransitionRecall(before.status as RecallStatus, input.status as RecallStatus) : canTransitionFollowUp(before.status as FollowUpStatus, input.status as FollowUpStatus); if (!okay) throw new ConflictError(`Illegal transition ${before.status} → ${input.status}`); if (before.status === input.status) return before; if (entity === 'campaign' && input.status === 'approved' && p.role !== 'hq') throw new ForbiddenError('Only HQ can approve a campaign'); const table = entity === 'lead' ? 'leads' : entity === 'campaign' ? 'campaigns' : entity === 'recall' ? 'recall_cases' : 'follow_up_cases'; const dbTable = entity === 'lead' ? leads : entity === 'campaign' ? campaigns : entity === 'recall' ? recallCases : followUpCases; const updated = await this.repo.updateStatus(tx, dbTable, p.orgId, id, input.status, input.outcome ?? null, entity === 'campaign' && input.status === 'approved' ? { approvedAt: new Date(), approvedBy: p.staffId } : undefined); if (!updated) throw new NotFoundError(entity,id); await this.audit.record(this.auditEvent(p, `marketing_${entity}_${input.status}`, table, id, before.branchId, { status: before.status }, { status: input.status, outcome: input.outcome ?? null }), tx); return updated; }); }
  transitionLead(p: Principal,id:string,raw:unknown){ return this.transition(p,id,raw,'lead'); }
  transitionCampaign(p: Principal,id:string,raw:unknown){ return this.transition(p,id,raw,'campaign'); }
  transitionRecall(p: Principal,id:string,raw:unknown){ return this.transition(p,id,raw,'recall'); }
  transitionFollowUp(p: Principal,id:string,raw:unknown){ return this.transition(p,id,raw,'followUp'); }
}
